# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15uHtPey1XR_HDf5PO0413ItinRarmp9t
"""

import streamlit as st



st.set_page_config(page_title="🌸 Your Mood, My Song 💖  Made by apka Vishwas")

st.title("🎵 Your Mood, My 90s Hindi Song 💕")
st.write("Hey love! Tell me your mood, and I'll dedicate a song just for you 💌")

# Mood options
moods = [
    "Happy 😊",
    "Romantic 💖",
    "Sad 😢",
    "Stressed 😥",
    "Energetic ⚡",
    "Missing You 💭",
    "Angry 😠"
]

selected_mood = st.selectbox("How are you feeling today?", moods)

# Song + message mapping (90s Hindi songs)
songs = {
    "Happy 😊": {
        "message": "When you're happy, I just want to dance with you forever!",
        "link": "https://youtu.be/Achfeohm57k?si=IjYB_laF-4xMYfVh"
    },
    "Romantic 💖": {
        "message": "This song says everything my heart feels when I think of you.",
        "link": "https://youtu.be/pVUM3WS_1Hc?si=__Cyopjij306H1VS"
    },
    "Sad 😢": {
        "message": "When you're sad, remember I'll always be your shoulder to lean on.",
        "link": "https://youtu.be/oDfK3RfSlKk?si=JPFgFOyzlSHchU6X"
    },
    "Stressed 😥": {
        "message": "Let this peaceful tune calm your beautiful mind.",
        "link": "https://youtu.be/PR_mFnjFidk?si=I2I_z2ybkh2b4Q4K"
    },
    "Energetic ⚡": {
        "message": "You and I dancing to this — unstoppable!",
        "link": "https://youtu.be/n_oP9Onj0r0?si=7jh7qzMJkg1CN2q0"
    },
    "Missing You 💭": {
        "message": "This song plays in my head every time I miss you.",
        "link": "https://youtu.be/yxYQZ4txt7E?si=C0Fm15cQ9b0hyeKX"
    },
    "Angry 😠": {
        "message": "Even when you're angry, you're my cutest! Let this song cool you down.",
        "link": "https://youtu.be/1LPtNHJckpw?si=jPM8luZbc6tG56Pc"
    }
}

if st.button("Show My Song 🎶"):
    song = songs[selected_mood]
    st.subheader(f"💌 {song['message']}")
    st.write(f"[Click here to listen!]({song['link']})")
    st.video(song['link'])

